name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build PT docs
        run: ./<path-to-mkdocs> build --config-file=mkdocs.pt.yml

      - name: Build EN docs
        run: ./<path-to-mkdocs> build --config-file=mkdocs.en.yml  

      # Copy blog/index.html to the root of site directory
      - name: Copy blog/index.html
        run: cp blog/index.html site/index.html

      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install mkdocs-material 

      - run: pip install mike --force-reinstall --verbose

      # Additional steps as needed for deployment
